### ISSUE TITLE
Description should not be mandatory on prediction create

### ISSUE THREAD

**Issue by Kattenelvis** [Gofven/flowback-backend#117]

**Comment by Gofven** [comment]
This should already been fixed, test and see if it works!

**Comment by Kattenelvis** [comment]
Still doesn't work

**Comment by Kattenelvis** [comment]
TypeError at /group/poll/5/prediction/statement/create
poll_prediction_statement_create() missing 1 required positional argument: 'description'


Traceback (most recent call last):
  File "D:\Files\flowback-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Files\flowback-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               
  File "C:\Users\Katte\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Files\flowback-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Files\flowback-backend\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
    ^^^^^^^^^
  File "D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Files\flowback-backend\flowback\poll\views\prediction.py", line 130, in post
    created_id = poll_prediction_statement_create(poll=poll_id,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Exception Type: TypeError at /group/poll/5/prediction/statement/create
Exception Value: poll_prediction_statement_create() missing 1 required positional argument: 'description'
Raised during: flowback.poll.views.prediction.PollPredictionStatementCreateAPI

**Comment by Gofven** [comment]
Try and see if it works nao!
