### ISSUE TITLE
AttributeError at /group/1/kanban/entry/delete 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by Kattenelvis** [Gofven/flowback-backend#132]
Traceback (most recent call last):
  File "D:\Files\flowback-backend\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Files\flowback-backend\venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               
  File "C:\Users\Katte\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Files\flowback-backend\venv\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Files\flowback-backend\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
    ^^^^^^^^^
  File "D:\Files\flowback-backend\venv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Files\flowback-backend\flowback\group\views\kanban.py", line 55, in post
    group_kanban_entry_delete(group_id=group_id, fetched_by_id=request.user.id, **serializer.validated_data)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Files\flowback-backend\flowback\group\services\kanban.py", line 61, in group_kanban_entry_delete
    work_group=work_group.id)
               ^^^^^^^^^^^^^

Exception Type: AttributeError at /group/1/kanban/entry/delete
Exception Value: 'NoneType' object has no attribute 'id'
Raised during: flowback.group.views.kanban.GroupKanbanEntryDeleteAPI

**Comment by Gofven** [comment]
Try and see if it works now c:

**Comment by Kattenelvis** [comment]
Doesn't work, however I have some juicy data that will make this easier to fix: The problem only occurs whenever there is no assignee (or assignee is set to null). So make sure there's some check against that or someone could use postman to sabotage a kanban board with spam.

**Comment by Gofven** [comment]
Is that relevant to this issue, group kanban entry delete don't have anything to do with assignees to do based on what i read
