### ISSUE TITLE
Delete comment error 500

### ISSUE THREAD

**Issue by Kattenelvis** [Gofven/flowback-backend#37]
AttributeError at /group/poll/32/comment/36/delete
'User' object has no attribute 'permission'

Traceback (most recent call last):
  File "/home/emil/flowback_backend/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/flowback_backend/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/flowback_backend/venv/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/flowback_backend/venv/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/flowback_backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/flowback_backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/flowback_backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
    ^^^^^^^^^
  File "/home/emil/flowback_backend/venv/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/flowback_backend/flowback/comment/views.py", line 105, in post
    self.lazy_action.__func__(*args,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/flowback_backend/flowback/poll/services/comment.py", line 53, in poll_comment_delete
    force = bool(group_user_permissions(group_user=fetched_by,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emil/flowback_backend/flowback/group/selectors.py", line 64, in group_user_permissions
    user_permissions = model_to_dict(group_user.permission) if group_user.permission else group_default_permissions(
                                                               ^^^^^^^^^^^^^^^^^^^^^

Exception Type: AttributeError at /group/poll/32/comment/36/delete
Exception Value: 'User' object has no attribute 'permission'

**Comment by Gofven** [comment]
see if it works now c:
