### ISSUE TITLE
Error 500 at delegation pool create

### ISSUE THREAD

**Issue by Kattenelvis** [Gofven/flowback-backend#74]
TypeError at /api/group/1/delegate/pool/create
GroupUserDelegate() got unexpected keyword arguments: 'blockchain_id'

Traceback (most recent call last):
  File "/home/emil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/emil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/emil/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/emil/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/emil/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/emil/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/emil/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/emil/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/emil/Desktop/Flowbacko Server Siamand/backend/flowback/group/views/delegate.py", line 107, in post
    group_user_delegate_pool_create(user=request.user.id, group=group, **serializer.validated_data)
  File "/home/emil/Desktop/Flowbacko Server Siamand/backend/flowback/group/services.py", line 382, in group_user_delegate_pool_create
    user_delegate = GroupUserDelegate(group_id=group,
  File "/home/emil/.local/lib/python3.10/site-packages/django/db/models/base.py", line 567, in __init__
    raise TypeError(

**Comment by Gofven** [comment]
Done c:
