### ISSUE TITLE
Thread list error 500

### ISSUE THREAD

**Issue by Kattenelvis** [Gofven/flowback-backend#76]
TypeError at /api/group/1/thread/list
QuerySet.annotate() received non-expression(s): {'active': True}.

Traceback (most recent call last):
  File "/home/emil/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
  File "/home/emil/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 253, in _get_response_async
    response = await wrapped_callback(
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/emil/.local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/home/emil/.local/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/emil/.local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/emil/.local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/emil/.local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/emil/.local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/emil/Desktop/Flowbacko Server Siamand/backend/flowback/group/views/thread.py", line 38, in get
    threads = group_thread_list(group_id=group_id, fetched_by=request.user, filters=serializer.validated_data)
  File "/home/emil/Desktop/Flowbacko Server Siamand/backend/flowback/group/selectors.py", line 268, in group_thread_list
    qs = GroupThread.objects.filter(created_by__group_id=group_id
  File "/home/emil/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
  File "/home/emil/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1600, in _annotate
    self._validate_values_are_expressions(
  File "/home/emil/.local/lib/python3.10/site-packages/django/db/models/query.py", line 1950, in _validate_values_are_expressions
    raise TypeError(

**Comment by Gofven** [comment]
Test and see if it works c:

**Comment by Kattenelvis** [comment]
This has been fixed, but a new error has occurred on thread list
